### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/Memelabs#8]
```
2024-11-17 16:30:58 | SUCCESS  | 63 - No change in api!
Traceback (most recent call last):
  File "/home/bots/Memelabs/bot/core/tapper.py", line 141, in login
    res = await login.json()
          ^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1166, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.memeslab.xyz/auth/login?....')
2024-11-17 16:30:59 | ERROR    | 152 - Name | Unknown error while trying to login: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.memeslab.xyz/auth/login?user=%
```

**Comment by tnttol** [comment]
please don't write to me that I'm banned

**Comment by Karh3030** [comment]
> please don't write to me that I'm banned

np. you are not banned =)
